import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  listItem: {
    margin: 10,
    padding: 70,
    paddingVertical: -10,
    backgroundColor: "white",
    flex: 1 / 2,
    flexDirection: "column",
  },
  flatList: {
    textAlign: "center",
    textAlignVertical: "center",
  },
  container4: {
    flex: 1,
    paddingTop: 60,
    flexDirection: "column",
    backgroundColor: "#ffffff",
  },
  titleStyle: {
    margin: 10,
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    alignSelf: "stretch",
  },
  headerText: {
    fontSize: 20,
    textAlign: "center",
    margin: 10,
    fontWeight: "bold",
  },
  container: {
    flex: 1,
    backgroundColor: "#F1F1F1",
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    marginBottom: 50,
    width: 200,
    height: 190,
  },
  image4: {
    marginBottom: 10,
    width: 200,
    height: 190,
  },
  image2: {
    width: 20,
    height: 20,
  },
  image3: {
    width: 80,
    height: 80,
  },
  inputView: {
    backgroundColor: "#FFF",
    borderRadius: 30,
    width: "80%",
    height: 45,
    marginBottom: 20,
    borderColor: "#b3b3b3",
    borderWidth: 1,
  },
  inputView2: {
    backgroundColor: "#FFF",
    borderRadius: 30,
    width: "80%",
    height: 45,
    marginBottom: 10,
    borderColor: "#b3b3b3",
    borderWidth: 1,
  },
  inputView3: {
    backgroundColor: "#FFF",
    borderRadius: 30,
    width: "80%",
    height: 45,
    marginBottom: 10,
    borderColor: "#b3b3b3",
    borderWidth: 1,
    overflow: "hidden",
  },
  TextInput: {
    height: 45,
    flex: 1,
    padding: 10,
    marginLeft: 0,
    position: "absolute",
    color: "#E1604D",
  },
  TextInput31: {
    alignSelf: "flex-end",
    height: 45,
    flex: 1,
    color: "#E1604D",
  },
  TextInput5: {
    fontSize: 13,
    textAlign: "center",
    color: "grey",
  },
  loginText: {
    fontSize: 20,
  },
  ForgetText: {
    fontSize: 12,
    color: "#E1604D",
  },
  ForgetText2: {
    fontSize: 12,
    color: "black",
  },
  ContinueravecText: {
    fontSize: 20,
  },
  oauthTxt: {
    fontSize: 20,
  },
  inscrire: {
    fontSize: 16,
    fontWeight: "bold",
    height: 30,
    marginBottom: 40,
  },
  inscrire4: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 40,
  },
  inscrire3: {
    fontSize: 25,
    fontWeight: "bold",
    marginBottom: 40,
  },
  inscrire2: {
    fontSize: 20,
    fontWeight: "bold",
    height: 30,
    marginTop: 30,
    marginBottom: 30,
  },
  loginBtn: {
    width: "80%",
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: "#E1604D",
    borderColor: "#b3b3b3",
    borderWidth: 1,
  },
  loginBtn2: {
    width: "80%",
    right: -31,
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    marginBottom: 10,
    backgroundColor: "#E1604D",
    borderColor: "#b3b3b3",
    borderWidth: 1,
  },
  FPBtn: {
    width: "80%",
    borderRadius: 25,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
    marginBottom: 0,
    backgroundColor: "#00000000",
  },
  oauthBtn: {
    width: "40%",
    borderRadius: 25,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20,
    backgroundColor: "#f5f5f5",
  },
});

export default styles;
